"""DynamoDB Stack for BADGERS job tracking.

Ported from the media-contracts (MC) reference implementation.

Table: badgers-jobs-{deployment_id}
  PK  job_id      (String) — uuid generated by the caller, idempotency key
  SK  specialist  (String) — 'orchestrator' | any specialist name registered in
                             lambdas/code or custom_specialists
                             (e.g. 'handwriting_specialist', 'full_text_specialist')

Attributes (written by the orchestrator runtime and each specialist Lambda):
  status        : PENDING | RUNNING | COMPLETE | FAILED
  result_s3_key : S3 key where the specialist output was written
  started_at    : ISO-8601 timestamp
  completed_at  : ISO-8601 timestamp
  error         : error message (FAILED only)
  retry_count   : int
  ttl           : epoch seconds — records auto-expire after 30 days

GSI: status-index
  PK  status     — query all jobs in a given state (ops/monitoring, UI filters)
  SK  started_at

Unlike MC, BADGERS specialists are dynamic (registered by directory discovery and
by the custom specialist registry), so the sort key is not constrained to a fixed
enum.
"""

from aws_cdk import (
    RemovalPolicy,
    Stack,
    Tags,
    CfnOutput,
    aws_dynamodb as dynamodb,
    aws_ssm as ssm,
)
from constructs import Construct


class DynamoDBStack(Stack):
    """DynamoDB table for specialist job state and checkpointing."""

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        deployment_id: str,
        deployment_tags: dict[str, str],
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.deployment_id = deployment_id
        self.deployment_tags = deployment_tags
        self._apply_common_tags()

        # ── Jobs table ─────────────────────────────────────────────
        self.jobs_table = dynamodb.Table(
            self,
            "SpecialistJobs",
            table_name=f"badgers-jobs-{deployment_id}",
            partition_key=dynamodb.Attribute(
                name="job_id",
                type=dynamodb.AttributeType.STRING,
            ),
            sort_key=dynamodb.Attribute(
                name="specialist",
                type=dynamodb.AttributeType.STRING,
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            point_in_time_recovery_specification=dynamodb.PointInTimeRecoverySpecification(
                point_in_time_recovery_enabled=True,
            ),
            encryption=dynamodb.TableEncryption.AWS_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
            time_to_live_attribute="ttl",
        )

        # GSI for ops monitoring and UI status filters
        self.jobs_table.add_global_secondary_index(
            index_name="status-index",
            partition_key=dynamodb.Attribute(
                name="status",
                type=dynamodb.AttributeType.STRING,
            ),
            sort_key=dynamodb.Attribute(
                name="started_at",
                type=dynamodb.AttributeType.STRING,
            ),
            projection_type=dynamodb.ProjectionType.INCLUDE,
            non_key_attributes=[
                "job_id",
                "specialist",
                "result_s3_key",
                "error",
                "completed_at",
            ],
        )

        # ── SSM parameter for runtime discovery ────────────────────
        ssm.StringParameter(
            self,
            "JobsTableParam",
            parameter_name=f"/badgers-{deployment_id}/jobs-table-name",
            string_value=self.jobs_table.table_name,
            description="DynamoDB jobs table name",
        )

        self._apply_resource_tags(
            self.jobs_table,
            "specialist-jobs-table",
            "DynamoDB table for BADGERS specialist job tracking",
        )

        # ── Outputs ────────────────────────────────────────────────
        CfnOutput(
            self,
            "JobsTableName",
            value=self.jobs_table.table_name,
            description="DynamoDB jobs table name",
            export_name=f"{Stack.of(self).stack_name}-JobsTableName",
        )
        CfnOutput(
            self,
            "JobsTableArn",
            value=self.jobs_table.table_arn,
            description="DynamoDB jobs table ARN",
            export_name=f"{Stack.of(self).stack_name}-JobsTableArn",
        )

    def _apply_common_tags(self) -> None:
        for key, value in self.deployment_tags.items():
            Tags.of(self).add(key, value)

    def _apply_resource_tags(
        self, resource: Construct, name: str, description: str
    ) -> None:
        Tags.of(resource).add("resource_name", name)
        Tags.of(resource).add("resource_description", description)
