#!/bin/bash
# Updates frontend/.env with CDK stack outputs after deployment
# Usage: ./update_frontend_env.sh [--profile PROFILE]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../frontend/config/.env"
STACK_PREFIX="badgers"

# Parse arguments
_AWS_PROFILE_ARG=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --profile)
            _AWS_PROFILE_ARG="--profile $2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

echo "Fetching CDK outputs..."

# Get outputs from each stack
get_output() {
    local stack=$1
    local key=$2
    aws cloudformation describe-stacks \
        --stack-name "$stack" \
        --query "Stacks[0].Outputs[?OutputKey=='$key'].OutputValue" \
        --output text $_AWS_PROFILE_ARG 2>/dev/null || echo ""
}

# Fetch the values we need
RUNTIME_WEBSOCKET_ARN=$(get_output "${STACK_PREFIX}-runtime-websocket" "RuntimeArn")
GATEWAY_ID=$(get_output "${STACK_PREFIX}-gateway" "GatewayId")
S3_UPLOAD_BUCKET=$(get_output "${STACK_PREFIX}-s3" "SourceBucketName")
S3_OUTPUT_BUCKET=$(get_output "${STACK_PREFIX}-s3" "OutputBucketName")
S3_CONFIG_BUCKET=$(get_output "${STACK_PREFIX}-s3" "ConfigBucketName")

# Validate we got required values
if [[ -z "$RUNTIME_WEBSOCKET_ARN" || -z "$GATEWAY_ID" || -z "$S3_UPLOAD_BUCKET" || -z "$S3_OUTPUT_BUCKET" || -z "$S3_CONFIG_BUCKET" ]]; then
    echo "Error: Could not fetch all required outputs"
    echo "  RUNTIME_WEBSOCKET_ARN: ${RUNTIME_WEBSOCKET_ARN:-MISSING}"
    echo "  GATEWAY_ID: ${GATEWAY_ID:-MISSING}"
    echo "  S3_UPLOAD_BUCKET: ${S3_UPLOAD_BUCKET:-MISSING}"
    echo "  S3_OUTPUT_BUCKET: ${S3_OUTPUT_BUCKET:-MISSING}"
    echo "  S3_CONFIG_BUCKET: ${S3_CONFIG_BUCKET:-MISSING}"
    exit 1
fi

# Preserve existing AWS_REGION and AWS_PROFILE from .env
if [[ -f "$ENV_FILE" ]]; then
    AWS_REGION=$(grep "^AWS_REGION=" "$ENV_FILE" | cut -d'=' -f2)
    AWS_PROFILE=$(grep "^AWS_PROFILE=" "$ENV_FILE" | cut -d'=' -f2)
fi

# Defaults if not found
AWS_REGION=${AWS_REGION:-us-west-2}
AWS_PROFILE=${AWS_PROFILE:-default}

# Write updated .env
cat > "$ENV_FILE" << EOF
# AWS Configuration
AWS_REGION=$AWS_REGION
AWS_PROFILE=$AWS_PROFILE

# S3 Buckets
S3_UPLOAD_BUCKET=$S3_UPLOAD_BUCKET
S3_OUTPUT_BUCKET=$S3_OUTPUT_BUCKET
S3_CONFIG_BUCKET=$S3_CONFIG_BUCKET

# =============================================================================
# AgentCore Configuration
# =============================================================================
# AgentCore Runtime Configuration
# Auto-generated by update_frontend_env.sh

# AgentCore Runtime ARN for WebSocket streaming
AGENTCORE_RUNTIME_ARN=$RUNTIME_WEBSOCKET_ARN
AGENTCORE_RUNTIME_WEBSOCKET_ARN=$RUNTIME_WEBSOCKET_ARN

# AgentCore Gateway ID (for listing tools)
AGENTCORE_GATEWAY_ID=$GATEWAY_ID

# AgentCore Client Timeouts (for long-running agent operations)
# Read timeout in seconds - how long to wait for agent response
# Default: 600 (10 minutes) - increase for very long PDF analysis
AGENTCORE_READ_TIMEOUT=600

# Connect timeout in seconds - how long to wait for initial connection
AGENTCORE_CONNECT_TIMEOUT=30

# Max retry attempts - SET TO 1 TO DISABLE RETRIES
# IMPORTANT: Retries cause duplicate invocations and conversation corruption!
AGENTCORE_MAX_RETRIES=1

# =============================================================================
# AgentCore Control Plane Timeouts (for fast operations like listing tools)
# =============================================================================
AGENTCORE_CONTROL_PLANE_READ_TIMEOUT=30
AGENTCORE_CONTROL_PLANE_CONNECT_TIMEOUT=10
AGENTCORE_CONTROL_PLANE_MAX_RETRIES=3
EOF

echo "Updated $ENV_FILE:"
echo "  AGENTCORE_RUNTIME_ARN=$RUNTIME_WEBSOCKET_ARN"
echo "  AGENTCORE_RUNTIME_WEBSOCKET_ARN=$RUNTIME_WEBSOCKET_ARN"
echo "  AGENTCORE_GATEWAY_ID=$GATEWAY_ID"
echo "  S3_UPLOAD_BUCKET=$S3_UPLOAD_BUCKET"
echo "  S3_OUTPUT_BUCKET=$S3_OUTPUT_BUCKET"
echo "  S3_CONFIG_BUCKET=$S3_CONFIG_BUCKET"
echo "  (AWS_REGION and AWS_PROFILE preserved)"
