#!/usr/bin/env bash
# Generate ui/.env from the Cognito CDK stack outputs.
#
# The generated values are baked into the Vite bundle at build time (Vite only
# exposes variables prefixed with VITE_), so this must run AFTER the Cognito
# stack is deployed and BEFORE the UI image is built.
#
# Usage:
#   DEPLOYMENT_ID=dev ./deployment/scripts/generate_ui_env.sh
#   DEPLOYMENT_ID=dev STACK_SUFFIX=a1b ./deployment/scripts/generate_ui_env.sh
#
# STACK_SUFFIX is read from .deploy-state/{DEPLOYMENT_ID}.json when not supplied.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

load_suffix
STACK_NAME="$(_sn Cognito)"

echo "==> Reading Cognito outputs from ${STACK_NAME} (${AWS_REGION})..."

get_output() {
    stack_output "${STACK_NAME}" "$1"
}

AUTHORITY=$(get_output "Authority")
UI_CLIENT_ID=$(get_output "UIClientId")
COGNITO_DOMAIN=$(get_output "CognitoDomain")

if [ -z "${AUTHORITY}" ] || [ "${AUTHORITY}" = "None" ] \
   || [ -z "${UI_CLIENT_ID}" ] || [ "${UI_CLIENT_ID}" = "None" ]; then
    echo "ERROR: Could not read Cognito outputs. Is ${STACK_NAME} deployed?"
    echo "  Authority:    '${AUTHORITY}'"
    echo "  UIClientId:   '${UI_CLIENT_ID}'"
    exit 1
fi

ENV_FILE="${REPO_ROOT}/ui/.env"

cat > "${ENV_FILE}" << EOF
# Auto-generated by deployment/scripts/generate_ui_env.sh — do not edit by hand.
# Re-run after redeploying ${STACK_NAME}.
#
# Vite only exposes VITE_-prefixed variables to the bundle. These are public
# values (an OIDC authority, a public PKCE client id, and a hosted UI domain);
# no secret is included here.
VITE_COGNITO_AUTHORITY=${AUTHORITY}
VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
EOF

echo "✓ Written to ${ENV_FILE}"
echo "    VITE_COGNITO_AUTHORITY=${AUTHORITY}"
echo "    VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}"
echo "    VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}"
echo ""
echo "Next: build the UI bundle and image, then deploy the ECS stack."
