#!/usr/bin/env bash
# Generate ui/.env from the badgers-cognito CDK stack outputs.
#
# The generated values are baked into the Vite bundle at build time (Vite only
# exposes variables prefixed with VITE_), so this must run AFTER the Cognito
# stack is deployed and BEFORE the UI image is built.
#
# Usage:
#   ./deployment/scripts/generate_ui_env.sh
#   AWS_REGION=us-west-2 STACK_PREFIX=badgers ./deployment/scripts/generate_ui_env.sh

set -euo pipefail

AWS_REGION="${AWS_REGION:-us-west-2}"
STACK_PREFIX="${STACK_PREFIX:-badgers}"
STACK_NAME="${STACK_PREFIX}-cognito"

# Resolve repo root from this script's location so it can be run from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

echo "==> Reading Cognito outputs from ${STACK_NAME} (${AWS_REGION})..."

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "${STACK_NAME}" \
        --region "${AWS_REGION}" \
        --query "Stacks[0].Outputs[?OutputKey=='${1}'].OutputValue" \
        --output text 2>/dev/null || echo ""
}

AUTHORITY=$(get_output "Authority")
UI_CLIENT_ID=$(get_output "UIClientId")
COGNITO_DOMAIN=$(get_output "CognitoDomain")

if [ -z "${AUTHORITY}" ] || [ "${AUTHORITY}" = "None" ] \
   || [ -z "${UI_CLIENT_ID}" ] || [ "${UI_CLIENT_ID}" = "None" ]; then
    echo "ERROR: Could not read Cognito outputs. Is ${STACK_NAME} deployed?"
    echo "  Authority:    '${AUTHORITY}'"
    echo "  UIClientId:   '${UI_CLIENT_ID}'"
    exit 1
fi

ENV_FILE="${REPO_ROOT}/ui/.env"

cat > "${ENV_FILE}" << EOF
# Auto-generated by deployment/scripts/generate_ui_env.sh — do not edit by hand.
# Re-run after redeploying ${STACK_NAME}.
#
# Vite only exposes VITE_-prefixed variables to the bundle. These are public
# values (an OIDC authority, a public PKCE client id, and a hosted UI domain);
# no secret is included here.
VITE_COGNITO_AUTHORITY=${AUTHORITY}
VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
EOF

echo "✓ Written to ${ENV_FILE}"
echo "    VITE_COGNITO_AUTHORITY=${AUTHORITY}"
echo "    VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}"
echo "    VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}"
echo ""
echo "Next: build the UI bundle and image, then deploy the ECS stack."
