#!/usr/bin/env bash
# Generate ui/.env — the single local-development env file — from the deployed stacks.
#
# Two kinds of value land in the one file:
#
#   VITE_*   Cognito OIDC values. Vite bakes these into the bundle at build time (it
#            only exposes VITE_-prefixed variables), so this must run AFTER the Cognito
#            stack is deployed and BEFORE the UI image is built. deploy.sh step 7 does.
#
#   others   Runtime values read by ui/server/index.js when running outside ECS: bucket
#            names, the Runtime ARN, the Gateway ID, the jobs table. Local convenience
#            only — the deployed container gets every one of these from SSM Parameter
#            Store. Nothing copies ui/.env into the image.
#
# AWS_PROFILE and AWS_REGION are written commented out: for local testing the terminal
# session supplies them, and process.env wins over this file in the server anyway.
# Operator-owned lines (an uncommented AWS_PROFILE/AWS_REGION, CORS_ALLOWED_ORIGIN,
# BADGERS_UI_ROLE, WS_TIMEOUT_MINUTES) are carried over on regeneration.
#
# Usage:
#   DEPLOYMENT_ID=dev ./deployment/scripts/generate_ui_env.sh
#   DEPLOYMENT_ID=dev STACK_SUFFIX=a1b ./deployment/scripts/generate_ui_env.sh
#
# STACK_SUFFIX is read from .deploy-state/{DEPLOYMENT_ID}.json when not supplied.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

load_suffix
# Region for reading the stacks: environment, then the active profile's configured
# region, then a prompt — not a silent us-west-2 default.
ensure_region
ENV_FILE="${REPO_ROOT}/ui/.env"

echo "==> Reading stack outputs for ${DEPLOYMENT_ID}-${STACK_SUFFIX} (${AWS_REGION})..."

# ── Cognito (build-time, required) ─────────────────────────────────────────
COGNITO_STACK="$(_sn Cognito)"
AUTHORITY=$(stack_output "${COGNITO_STACK}" "Authority")
UI_CLIENT_ID=$(stack_output "${COGNITO_STACK}" "UIClientId")
COGNITO_DOMAIN=$(stack_output "${COGNITO_STACK}" "CognitoDomain")
USER_POOL_ID=$(stack_output "${COGNITO_STACK}" "UserPoolId")

if [ -z "${AUTHORITY}" ] || [ "${AUTHORITY}" = "None" ] \
   || [ -z "${UI_CLIENT_ID}" ] || [ "${UI_CLIENT_ID}" = "None" ]; then
    echo "ERROR: Could not read Cognito outputs. Is ${COGNITO_STACK} deployed?"
    echo "  Authority:    '${AUTHORITY}'"
    echo "  UIClientId:   '${UI_CLIENT_ID}'"
    exit 1
fi

# ── Server runtime values (local dev; optional — stacks may not exist yet) ──
_opt() { local v; v="$(stack_output "$1" "$2")"; [ "${v}" = "None" ] && v=""; echo "${v}"; }
RUNTIME_WEBSOCKET_ARN=$(_opt "$(_sn RuntimeWebSocket)" "RuntimeArn")
GATEWAY_ID=$(_opt "$(_sn Gateway)" "GatewayId")
S3_UPLOAD_BUCKET=$(_opt "$(_sn S3)" "SourceBucketName")
S3_OUTPUT_BUCKET=$(_opt "$(_sn S3)" "OutputBucketName")
S3_CONFIG_BUCKET=$(_opt "$(_sn S3)" "ConfigBucketName")
JOBS_TABLE_NAME=$(_opt "$(_sn DynamoDB)" "JobsTableName")

# ── Carry operator-owned lines across regenerations ────────────────────────
_keep() {
    [ -f "${ENV_FILE}" ] || { echo ""; return; }
    # grep exits 1 on no match; under `set -eo pipefail` that would abort the script.
    { grep -E "^$1=" "${ENV_FILE}" || true; } | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'"
}
# AWS_PROFILE / AWS_REGION come from the terminal session by default and are written
# commented out. Only a line the operator has already uncommented in ui/.env is kept
# active — and even then process.env wins at runtime (ui/server/index.js, core.js).
_pinned_or_hint() {
    local key="$1" hint="$2" existing
    existing="$(_keep "${key}")"
    if [ -n "${existing}" ]; then echo "${key}=${existing}"; else echo "#${key}=${hint}"; fi
}
AWS_PROFILE_LINE="$(_pinned_or_hint AWS_PROFILE "<local profile override here>")"
AWS_REGION_LINE="$(_pinned_or_hint AWS_REGION "<local region override here>")"
CORS_ALLOWED_ORIGIN="$(_keep CORS_ALLOWED_ORIGIN)"
BADGERS_UI_ROLE="$(_keep BADGERS_UI_ROLE)"
WS_TIMEOUT_MINUTES="$(_keep WS_TIMEOUT_MINUTES)"; WS_TIMEOUT_MINUTES="${WS_TIMEOUT_MINUTES:-30}"

cat > "${ENV_FILE}" << EOF
# Auto-generated by deployment/scripts/generate_ui_env.sh — do not edit by hand.
# Re-run after redeploying ${DEPLOYMENT_ID}-${STACK_SUFFIX}:
#   DEPLOYMENT_ID=${DEPLOYMENT_ID} ./deployment/scripts/generate_ui_env.sh
#
# One file, two audiences:
#   VITE_*     baked into the browser bundle at build time (public values only).
#   everything else  read by ui/server/index.js for local development. The deployed
#                    container reads these from SSM instead; this file never ships.

# ── AWS ───────────────────────────────────────────────────────────────────────
# Credentials and region come from your terminal session (exported AWS_PROFILE /
# AWS_REGION, or the default credential chain). Uncomment to pin a fallback for
# when the shell has nothing set; an exported variable still wins.
${AWS_PROFILE_LINE}
${AWS_REGION_LINE}
DEPLOYMENT_ID=${DEPLOYMENT_ID}
STACK_SUFFIX=${STACK_SUFFIX}

# ── Cognito (build-time, public) ──────────────────────────────────────────────
VITE_COGNITO_AUTHORITY=${AUTHORITY}
VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}

# ── Cognito (server-side token verification) ──────────────────────────────────
# Leave COGNITO_USER_POOL_ID commented out to keep the local-dev auth bypass
# (ui/server/auth.js). Uncomment both to verify real tokens locally.
#COGNITO_USER_POOL_ID=${USER_POOL_ID}
#COGNITO_UI_CLIENT_ID=${UI_CLIENT_ID}
COGNITO_DOMAIN=${COGNITO_DOMAIN}
# Role for the bypassed dev identity: admin (default) or tester.
BADGERS_UI_ROLE=${BADGERS_UI_ROLE}

# ── S3 ────────────────────────────────────────────────────────────────────────
S3_UPLOAD_BUCKET=${S3_UPLOAD_BUCKET}
S3_OUTPUT_BUCKET=${S3_OUTPUT_BUCKET}
S3_CONFIG_BUCKET=${S3_CONFIG_BUCKET}

# ── DynamoDB jobs table. Without this the /api/jobs endpoints return 503. ─────
JOBS_TABLE_NAME=${JOBS_TABLE_NAME}

# ── AgentCore ─────────────────────────────────────────────────────────────────
AGENTCORE_RUNTIME_ARN=${RUNTIME_WEBSOCKET_ARN}
AGENTCORE_RUNTIME_WEBSOCKET_ARN=${RUNTIME_WEBSOCKET_ARN}
AGENTCORE_GATEWAY_ID=${GATEWAY_ID}

# Data-plane timeouts (seconds). Retries cause duplicate invocations and
# conversation corruption — keep AGENTCORE_MAX_RETRIES at 1.
AGENTCORE_READ_TIMEOUT=600
AGENTCORE_CONNECT_TIMEOUT=30
AGENTCORE_MAX_RETRIES=1

# Control-plane timeouts (listing tools etc.)
AGENTCORE_CONTROL_PLANE_READ_TIMEOUT=30
AGENTCORE_CONTROL_PLANE_CONNECT_TIMEOUT=10
AGENTCORE_CONTROL_PLANE_MAX_RETRIES=3

# ── Server ────────────────────────────────────────────────────────────────────
# Minutes to keep a WebSocket open before timing out.
WS_TIMEOUT_MINUTES=${WS_TIMEOUT_MINUTES}
# Extra allowed CORS origin (same-origin only when empty).
CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
EOF

echo "✓ Written to ${ENV_FILE}"
echo "    VITE_COGNITO_AUTHORITY=${AUTHORITY}"
echo "    VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}"
echo "    VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}"
echo "    AGENTCORE_RUNTIME_WEBSOCKET_ARN=${RUNTIME_WEBSOCKET_ARN:-<not deployed>}"
echo "    AGENTCORE_GATEWAY_ID=${GATEWAY_ID:-<not deployed>}"
echo "    S3_UPLOAD_BUCKET=${S3_UPLOAD_BUCKET:-<not deployed>}"
echo "    S3_OUTPUT_BUCKET=${S3_OUTPUT_BUCKET:-<not deployed>}"
echo "    S3_CONFIG_BUCKET=${S3_CONFIG_BUCKET:-<not deployed>}"
echo "    JOBS_TABLE_NAME=${JOBS_TABLE_NAME:-<not deployed>}"
echo "    ${AWS_PROFILE_LINE}   (terminal session wins)"
echo "    ${AWS_REGION_LINE}"
echo ""
echo "Next: build the UI bundle and image, then deploy the ECS stack."
